services:
  app:
    build: .
    container_name: PokeApi_observability
    ports:
      - "8001:8001"
    depends_on:
      - database
    networks:
      - sentinel
    env_file: .env

  database:
    image: postgres
    container_name: PokeApi_observability_db
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: pokeob
      POSTGRES_PASSWORD: pokeob
      POSTGRES_DB: pokeob
    command: postgres -c "port=5433" # Força o PostgreSQL a usar a porta 5433
    networks:
      - sentinel

networks:
  sentinel:
    external: true
